### ISSUE TITLE
Code utilisé dans le HS

### ISSUE THREAD

**Issue by sebo83910** [GLMF/GLMFHS90#1]
Bonjour,

Est-il possible d'avoir accès aux différents codes python utilisés dans ce super hors-série?
Merci!

**Comment by tcolombo** [comment]
Bonjour,

Malheureusement le HS date de 2017, c'est un peu ancien maintenant pour retrouver le code...

Cordialement

**Comment by sebo83910** [comment]
Dommage. Merci pour la réponse.
Continuez à nous faire des numéros de qualité. J'apprécie particulièrement ceux sur python.
Cdlt.
